#################################################################
#################   Automatically Generated   ###################

# @Owner:   Cohomology Labs Research Pvt Ltd
# @Owner's Website: https://cohomologylabs.tech
# @CreatedBy: ArvindSinc
# @Date:   10/01/2018

#################################################################

"""
DO NOT MAKE ANY MODIFICATION HERE

ALL THE SETTINGS NEED TO BE DONE IN THE MAIN CONFIG.PY FILE

THIS PYTHON FILE IMPORTS SETTINGS FROM MAIN PYTHON FILE
"""

import sys
sys.path.insert(0, '../')

#DO NOT EDIT THIS FILE