#################################################################
#################   Automatically Generated   ###################

# @Owner:   Cohomology Labs Research Pvt Ltd
# @Owner's Website: https://cohomologylabs.tech
# @CreatedBy: ArvindSinc
# @Date:   10/01/2018

#################################################################

"""
DO NOT MAKE ANY MODIFICATION HERE

ALL THE SETTINGS NEED TO BE DONE IN THE MAIN CONFIG.PY FILE

THIS PYTHON FILE IMPORTS SETTINGS FROM MAIN PYTHON FILE
"""

import sys
sys.path.insert(0, '../')
from config import PILVO_AUTH_ID as mPILVO_AUTH_ID 
from config import PILVO_AUTH_TOKEN as mPILVO_AUTH_TOKEN
from config import PILVO_DEFAULT_SOURCE_NUMBER as mPILVO_DEFAULT_SOURCE_NUMBER

from config import TWILIO_ACCOUNT_SID as mTWILIO_ACCOUNT_SID
from config import TWILIO_AUTH_TOKEN as mTWILIO_AUTH_TOKEN
from config import TWILIO_DEFAULT_SOURCE_NUMBER as mTWILIO_DEFAULT_SOURCE_NUMBER

from config import SMS_ENGINE as mSMS_ENGINE


PILVO_AUTH_ID = mPILVO_AUTH_ID
PILVO_AUTH_TOKEN = mPILVO_AUTH_TOKEN
PILVO_DEFAULT_SOURCE_NUMBER = mPILVO_DEFAULT_SOURCE_NUMBER

TWILIO_ACCOUNT_SID = mTWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN = mTWILIO_AUTH_TOKEN
TWILIO_DEFAULT_SOURCE_NUMBER =mTWILIO_DEFAULT_SOURCE_NUMBER

SMS_ENGINE = mSMS_ENGINE


# DO NOT EDIT THIS FILE